site_name: Kombinator Help
nav:
- Getting started:
  - App installation: ReferenceGuide/Bitrix/install.md
  - App setup: ReferenceGuide/Bitrix/setting.md
  - Creating a template: ReferenceGuide/Bitrix/creat.md
  - Template automation: ReferenceGuide/Bitrix/template-automation.md
  - Generating a document: UserInterface/Documents/add-document.md
- Application interface:
  - Fields: UserInterface/Templates/fields.md
  - Editing area: UserInterface/Templates/edit-area.md
  - Toolbar: UserInterface/Templates/tabs.md
  - File name mask: UserInterface/Templates/file-name-mask.md
  - Preview: UserInterface/Templates/preview.md
  - Keyboard shortcuts: UserInterface/Templates/keyboard-shortcuts.md
- Fields:
  - Text: ReferenceGuide/typesField/text.md
  - Integer: ReferenceGuide/typesField/integer.md
  - Decimal: ReferenceGuide/typesField/decimal.md
  - Boolean: ReferenceGuide/typesField/boolean.md
  - Date/Time: ReferenceGuide/typesField/datetime.md
  - Date: ReferenceGuide/typesField/date.md
  - Time: ReferenceGuide/typesField/time.md
  - Struct: ReferenceGuide/typesField/struct.md
  - List: ReferenceGuide/typesField/list.md
  - Picture: ReferenceGuide/typesField/picture.md
- Function:
  - Date and time:
    - date: ReferenceGuide/functions/Date/date.md
    - edate: ReferenceGuide/functions/Date/edate.md
    - eomonth: ReferenceGuide/functions/Date/eomonth.md
    - bomonth: ReferenceGuide/functions/Date/bomonth.md
    - datediff: ReferenceGuide/functions/Date/datediff.md
    - Today: ReferenceGuide/functions/Date/Today.md
    - dateshift: ReferenceGuide/functions/Date/dateshift.md
    - now: ReferenceGuide/functions/Date/now.md
    - time: ReferenceGuide/functions/Date/time.md
    - year: ReferenceGuide/functions/Date/year.md
    - datetime: ReferenceGuide/functions/Date/datetime.md
    - month: ReferenceGuide/functions/Date/month.md
    - day: ReferenceGuide/functions/Date/day.md
    - hour: ReferenceGuide/functions/Date/hour.md
    - minute: ReferenceGuide/functions/Date/minute.md
    - second: ReferenceGuide/functions/Date/second.md
    - weekday: ReferenceGuide/functions/Date/weekday.md
    - weeknum: ReferenceGuide/functions/Date/weeknum.md
  - Formatting:
    - formatDate: ReferenceGuide/functions/Morph/formatDate.md
    - formatNumber: ReferenceGuide/functions/Morph/formatNumber.md
    - integerToText: ReferenceGuide/functions/Morph/integerToText.md
    - инициалы: ReferenceGuide/functions/Morph/инициалы.md
    - окончание: ReferenceGuide/functions/Morph/окончание.md
    - склонение: ReferenceGuide/functions/Morph/склонение.md
    - транслит: ReferenceGuide/functions/Morph/транслит.md
    - форматВалюты: ReferenceGuide/functions/Morph/форматВалюты.md
    - форматДаты: ReferenceGuide/functions/Morph/форматДаты.md    
    - целоеСТекстом: ReferenceGuide/functions/Morph/целоеСТекстом.md
    - числоСТекстом: ReferenceGuide/functions/Morph/числоСТекстом.md    
  - Math:
    - round: ReferenceGuide/functions/Math/round.md
    - roundup: ReferenceGuide/functions/Math/roundup.md
    - rounddown: ReferenceGuide/functions/Math/rounddown.md
    - exp: ReferenceGuide/functions/Math/exp.md
    - ln: ReferenceGuide/functions/Math/ln.md
    - log10: ReferenceGuide/functions/Math/log10.md
  - List:
    - match: ReferenceGuide/functions/Lists/match.md
    - index: ReferenceGuide/functions/Lists/index.md
    - sort: ReferenceGuide/functions/Lists/sort.md
    - sortDescending: ReferenceGuide/functions/Lists/sortDescending.md
    - filter: ReferenceGuide/functions/Lists/filter.md
    - group: ReferenceGuide/functions/Lists/group.md
    - sum: ReferenceGuide/functions/Lists/sum.md
    - max: ReferenceGuide/functions/Lists/max.md
    - min: ReferenceGuide/functions/Lists/min.md
    - avg: ReferenceGuide/functions/Lists/avg.md
    - count: ReferenceGuide/functions/Lists/count.md
  - Logic:
    - if: ReferenceGuide/functions/Logic/if.md
  - Text:
    - length: ReferenceGuide/functions/Text/length.md
    - trim: ReferenceGuide/functions/Text/trim.md
    - upper: ReferenceGuide/functions/Text/upper.md
    - proper: ReferenceGuide/functions/Text/proper.md
    - mid: ReferenceGuide/functions/Text/mid.md
    - lower: ReferenceGuide/functions/Text/lower.md
    - find: ReferenceGuide/functions/Text/find.md
    - substitute: ReferenceGuide/functions/Text/substitute.md
    - repeat: ReferenceGuide/functions/Text/repeat.md
- Syntax:
  - Basic rules: ReferenceGuide/syntax/syntax.md
  - Where to use: ReferenceGuide/syntax/syntax-usage.md
- Directives:
  - Expression: ReferenceGuide/directives/expression.md
  - External: ReferenceGuide/directives/external.md
  - Condition expression: ReferenceGuide/directives/if.md
  - Switch: ReferenceGuide/directives/switch.md
  - For: ReferenceGuide/directives/for.md
  - Table: ReferenceGuide/directives/table.md
  - Picture: ReferenceGuide/directives/picture.md
- FAQ: UserInterface/FAQ.md
- Support: UserInterface/help.md
theme:
  name: material
  logo: img/logo2.png
  favicon: img/logo.png
  language: en
  font:
    text: Roboto
  features:
  - navigation.tracking
  - navigation.top
  - content.image-zoom
  hide:
  - header.title
  palette:
    scheme: default
    primary: deep purple
    accent: purple
plugins:
- blog
- search
- include-markdown
markdown_extensions:
- attr_list
- md_in_html
extra_javascript:
- javascripts/extra.js
- assets/header.js
- assets/nav-toggle.js
extra_css:
- assets/extra.css
- styles/view-toggle.css
- styles/header-fix.css
- styles/bitrix-only.css
docs_dir: manual
